stag_doc: HKLX.cpp File Reference
HKLX.cpp File Reference
#include "HKLX.h"
#include "stdint.h"
#include <stdio.h>
#include <string.h>
#include <sys/time.h>
#include <cstdlib>
#include "opencv2/core/core.hpp"
Functions
void hklx_decoder_initialise (hklx_decoder_t *hklx_decoder)
hklx_packet_t * hklx_packet_allocate (uint8_t length, uint8_t id, uint8_t cmd)
void hklx_packet_free (hklx_packet_t **hklx_packet)
uint16_t calculate_crc (const void *data)
hklx_packet_t * hklx_packet_decode_new (hklx_decoder_t *hklx_decoder)
hklx_packet_t * hklx_packet_decode (hklx_decoder_t *hklx_decoder)
int return_length (hklx_packet_t *query_packet)
Function Documentation
uint16_t calculate_crc (const void * data)
Definition at line 45 of file HKLX.cpp.
References CHKSUM_MASK, and MIN_PACKET_SIZE.
Referenced by HKLX::discover(), hklx_packet_decode(), hklx_packet_decode_new(), and HKLX::send().
{
    uint8_t *bytes = (uint8_t *) data;
    uint16_t crc;
    uint8_t CheckSum1 = bytes[0] ^ bytes[1] ^ bytes[2];
    for (int i = 0; i < ((int) bytes[0] - MIN_PACKET_SIZE); i++)
        CheckSum1 ^= bytes[5 + i];
    uint8_t CheckSum2 = ~(CheckSum1);
    CheckSum1 &= CHKSUM_MASK;
    CheckSum2 &= CHKSUM_MASK;
    crc = CheckSum1;
    crc |= CheckSum2 << 8;
    return crc;
}
void hklx_decoder_initialise (hklx_decoder_t * hklx_decoder)
Definition at line 21 of file HKLX.cpp.
References hklx_decoder_t::buffer_length, and hklx_decoder_t::crc_errors.
Referenced by HKLX::HKLX().
{
    hklx_decoder->buffer_length = 0;
    hklx_decoder->crc_errors = 0;
}
hklx_packet_t* hklx_packet_allocate (uint8_t length, uint8_t id, uint8_t cmd)
Definition at line 26 of file HKLX.cpp.
References hklx_packet_t::cmd, HEADER, hklx_packet_t::header, hklx_packet_t::id, MIN_PACKET_SIZE, and hklx_packet_t::packetsize.
Referenced by HKLX::discover(), hklx_packet_decode(), hklx_packet_decode_new(), main(), and Stag::sjb().
{
    hklx_packet_t *hklx_packet = (hklx_packet_t*) malloc(sizeof (hklx_packet_t) + length * sizeof (uint8_t));
    if (hklx_packet != NULL) {
        hklx_packet->header[0] = HEADER;
        hklx_packet->header[1] = HEADER;
        hklx_packet->packetsize = length + MIN_PACKET_SIZE;
        hklx_packet->id = id;
        hklx_packet->cmd = cmd;
    }
    return hklx_packet;
}
hklx_packet_t* hklx_packet_decode (hklx_decoder_t * hklx_decoder)
Definition at line 169 of file HKLX.cpp.
References hklx_decoder_t::buffer, hklx_decoder_t::buffer_length, calculate_crc(), hklx_packet_t::data, HEADER, hklx_packet_allocate(), and MIN_PACKET_SIZE.
Referenced by HKLX::recive().
{
    //THIS IS SUPER FUCKED
    uint16_t decode_iterator = 0;
    hklx_packet_t *hklx_packet = NULL;
    uint8_t id, length, cmd, header1, header2;
    uint16_t crc;
    while (decode_iterator + MIN_PACKET_SIZE <= hklx_decoder->buffer_length) {
        //header_lrc = hklx_decoder->buffer[decode_iterator++];
        header1 = hklx_decoder->buffer[decode_iterator++];
        header2 = hklx_decoder->buffer[decode_iterator];
        if (header1 == HEADER && header2 == HEADER) {
            decode_iterator++;
            length = hklx_decoder->buffer[decode_iterator++];
            id = hklx_decoder->buffer[decode_iterator++];
            cmd = hklx_decoder->buffer[decode_iterator++];
            //crc = hklx_decoder->buffer[decode_iterator++];
            //crc |= hklx_decoder->buffer[decode_iterator++] << 8;
            crc = hklx_decoder->buffer[decode_iterator++];
            crc |= hklx_decoder->buffer[decode_iterator++] << 8;
            //printf("%i\n",length);
            if (decode_iterator + length - MIN_PACKET_SIZE > hklx_decoder->buffer_length) {
                decode_iterator -= MIN_PACKET_SIZE;
                break;
            }
            if (crc == calculate_crc(&hklx_decoder->buffer[decode_iterator - MIN_PACKET_SIZE + 2])) {
                hklx_packet = hklx_packet_allocate(length - MIN_PACKET_SIZE, id, cmd);
                if (hklx_packet != NULL) {
                    memcpy(hklx_packet->data, &hklx_decoder->buffer[decode_iterator], (length - MIN_PACKET_SIZE) * sizeof (uint8_t));
                }
                decode_iterator += length;
                //decode_iterator += length- MIN_PACKET_SIZE;
                break;
            } else {
                printf("CRC ERROR\n");
                //decode_iterator -= (MIN_PACKET_SIZE);
                //decode_iterator -= (2);
                //decode_iterator += length- MIN_PACKET_SIZE;
                printf("%i %i %i %i %i\n", length, decode_iterator, hklx_decoder->buffer_length, id, cmd);
                hklx_packet = hklx_packet_allocate(length - MIN_PACKET_SIZE, id, cmd);
                if (hklx_packet != NULL) {
                    memcpy(hklx_packet->data, &hklx_decoder->buffer[decode_iterator], (length - MIN_PACKET_SIZE) * sizeof (uint8_t));
                }
                decode_iterator += length;
                //decode_iterator += length- MIN_PACKET_SIZE;
                break;
            }
        }
    }
    if (decode_iterator < hklx_decoder->buffer_length) {
        if (decode_iterator > 0) {
            memmove(&hklx_decoder->buffer[0], &hklx_decoder->buffer[decode_iterator], (hklx_decoder->buffer_length - decode_iterator) * sizeof (uint8_t));
            hklx_decoder->buffer_length -= decode_iterator;
        }
    } else hklx_decoder->buffer_length = 0;
    //printf("%i\n",hklx_decoder->buffer_length);
    return hklx_packet;
}
hklx_packet_t* hklx_packet_decode_new (hklx_decoder_t * hklx_decoder)
Definition at line 103 of file HKLX.cpp.
References hklx_decoder_t::buffer, hklx_decoder_t::buffer_length, calculate_crc(), hklx_packet_t::data, HEADER, hklx_packet_allocate(), and MIN_PACKET_SIZE.
Referenced by HKLX::query().
{
    hklx_packet_t *hklx_packet = NULL;
    uint8_t id, length, cmd, header1, header2;
    uint16_t crc;
    if (MIN_PACKET_SIZE <= hklx_decoder->buffer_length) {
        header1 = hklx_decoder->buffer[0];
        header2 = hklx_decoder->buffer[1];
        if (header1 == HEADER && header2 == HEADER) {//good
            length = hklx_decoder->buffer[2];
            id = hklx_decoder->buffer[3];
            cmd = hklx_decoder->buffer[4];
            crc = hklx_decoder->buffer[5];
            crc |= hklx_decoder->buffer[6] << 8;
            if (length == hklx_decoder->buffer_length) {//good
                if (crc == calculate_crc(&hklx_decoder->buffer[2])) {
                    hklx_packet = hklx_packet_allocate(length - MIN_PACKET_SIZE, id, cmd);
                    if (hklx_packet != NULL) {
                        memcpy(hklx_packet->data, &hklx_decoder->buffer[7], (length - MIN_PACKET_SIZE) * sizeof (uint8_t));
                    }
                    hklx_decoder->buffer_length = 0;
                    return hklx_packet; //must also flush com port
                } else {
                    //CRC ERROR
                    //printf("CRC ERROR\n");
                    printf("crc FAIL\n");
                    hklx_decoder->buffer_length = 0;
                    return hklx_packet; //must also flush com port
                }
            } else {//length fail
                printf("%i %i length FAIL\n", length, hklx_decoder->buffer_length);
                hklx_decoder->buffer_length = 0;
                return hklx_packet; //must also flush com port
            }
        } else {//header error
            printf("head FAIL\n");
            hklx_decoder->buffer_length = 0;
            return hklx_packet; //must also flush com port
        }
    }
    printf("gen FAIL\n");
    //printf("%i\n",hklx_decoder->buffer_length);
    hklx_decoder->buffer_length = 0;
    return hklx_packet;
}
void hklx_packet_free (hklx_packet_t ** hklx_packet)
Definition at line 40 of file HKLX.cpp.
Referenced by main(), HKLX::poll(), HKLX::query(), HKLX::recive(), and Stag::sjb().
{
    free(*hklx_packet);
    *hklx_packet = NULL;
}
int return_length (hklx_packet_t * query_packet)
Definition at line 426 of file HKLX.cpp.
References hklx_packet_t::data.
Referenced by HKLX::query().
{
    return 7 + 4 + query_packet->data[1];
}