stag_doc: Stag.cpp File Reference
Stag.cpp File Reference
#include "Stag.h"
#include <cstdlib>
Functions
Mat rot_xyz (Mat in, float phi, int ax)
int main ()
Function Documentation
int main ()
Definition at line 259 of file Stag.cpp.
References Stag::body_jogn(), BROADCAST_ID, CMD_RAM_WRITE, COS_GAIT, hklx_packet_t::data, Stag::dp, Stag::gait_ratio, Stag::hklx, hklx_packet_allocate(), hklx_packet_free(), Stag::phase, Stag::phase_gait(), rot_xyz(), HKLX::send(), sixmotion::state(), Stag::stride, Stag::tic, and Stag::tic_time.
           {
    sixmotion six;
    Stag stag;
    hklx_packet_t *hklx_packet;
    hklx_packet = hklx_packet_allocate(3, BROADCAST_ID, CMD_RAM_WRITE);
    hklx_packet->data[0] = 0x34;
    hklx_packet->data[1] = 0x01;
    hklx_packet->data[2] = 0x60; //torque on
    stag.hklx.send(hklx_packet);
    hklx_packet_free(&hklx_packet);
    Mat leg_xyz = Mat::zeros(3, 4, CV_32F);
    stag.tic_time = (double) getTickCount();
    stag.body_jogn(leg_xyz, 200);
    usleep(400 * 10000);
    _sixmotion sixm;
    stag.tic_time = (double) getTickCount();
    float v = 0.1; //velocity in m/s
    stag.dp = (float) stag.tic * (v / (2.0f * stag.stride / stag.gait_ratio)) * 11200.0f / 1000000.0f;
    //dp is the velocity
    while (1) {
        sixm = six.state();
        leg_xyz = stag.phase_gait(COS_GAIT);
        Mat bcm = Mat::eye(3, 3, CV_32F);
        float direction =0.0f;//walking direction in RAD anti clockwise positive about Z
        leg_xyz = rot_xyz(bcm, direction, 2)*leg_xyz;
        //stag.body_rj(leg_xyz, stag.tic);
        stag.body_jogn(leg_xyz, stag.tic);
        stag.phase += stag.dp;
    }
    return 0;
}
Mat rot_xyz (Mat in, float phi, int ax)
Definition at line 11 of file Stag.cpp.
Referenced by Stag::body_jogn(), and main().
{
    float* u = in.ptr<float>(0);
    float u1 = u[ax];
    float u2 = u[3 + ax];
    float u3 = u[6 + ax];
    Mat Ux = (Mat_<float>(3, 3) <<
            0.0f, -u3, u2,
            u3, 0, -u1,
            -u2, u1, 0);
    Mat UxU = (Mat_<float>(3, 3) <<
            u1*u1, u1*u2, u1*u3,
            u1*u2, u2*u2, u2*u3,
            u1*u3, u2*u3, u3 * u3);
    Mat I = Mat::eye(3, 3, CV_32F);
    Mat R = I * cos(phi) + sin(phi) * Ux + (1 - cos(phi)) * UxU;
    return R*in;
}