stag_doc: HKLX Class Reference
HKLX Class Reference
#include <stagsrc/src/HKLX.h>
Public Member Functions
HKLX ()
HKLX (const HKLX &orig)
virtual ~HKLX ()
void add2queue ()
void hklx_packet_parse (hklx_packet_t *hklx_packet)
void discover ()
void send (hklx_packet_t *hklx_packet)
void state (_hklx out[])
int recive ()
void poll ()
Static Public Member Functions
static void * loop (void *obj)
Data Fields
double fr
double start
Private Member Functions
int query (hklx_packet_t *query_packet)
Private Attributes
bool active
pthread_t thread
test_struct * queue
test_struct * prv
std::vector< int > connected_id
std::vector< int > state_ready
pthread_mutex_t m_mut
_hklx id [254]
hklx_decoder_t hklx_decoder
int hklx_fd
Detailed Description
Definition at line 310 of file HKLX.h.
Constructor & Destructor Documentation
HKLX::HKLX ()
Definition at line 485 of file HKLX.cpp.
References BAUD, HKLX_COM, hklx_decoder_initialise(), and OpenComport().
           {
    //hklx_fd = OpenComport(HKLX_COM, BAUD,500000);
    hklx_fd = OpenComport(HKLX_COM, BAUD, 666666);
    hklx_decoder_initialise(&hklx_decoder);
    //hklx_packet_t *hklx_packet = hklx_packet_allocate(3, BROADCAST_ID, CMD_EEP_WRITE);
    //hklx_packet->data[0] = 0x04;
    //hklx_packet->data[1] = 0x01;
    //hklx_packet->data[2] = 0x02;
    //hklx_send(hklx_packet);
    //hklx_send(hklx_packet);
    //hklx_packet_free(&hklx_packet);
    //printf("done\n");
    //usleep(100000000000000);
    queue = NULL;
    discover();
    active = 1;
    //usleep(100000000000000);
    pthread_mutex_init(&m_mut, NULL);
    start = (double) getTickCount();
    fr = 0;
    //pthread_create(&thread, 0, &HKLX::loop, this);
}
HKLX::HKLX (const HKLX & orig)
Definition at line 522 of file HKLX.cpp.
{
}
HKLX::~HKLX () [virtual]
Definition at line 525 of file HKLX.cpp.
            {
    if (active == 0) {
        pthread_mutex_destroy(&m_mut);
        pthread_join(thread, 0);
    }
}
Member Function Documentation
void HKLX::add2queue ()
Definition at line 747 of file HKLX.cpp.
References test_struct::del, test_struct::next, and test_struct::val.
                     {
    //printf("TRYLOCKA\n");
    pthread_mutex_lock(&m_mut);
    //printf("lock a\n");
    test_struct *ptr;
    ptr = (test_struct*) malloc(sizeof (test_struct));
    ptr->val = 244;
    ptr->del = 1;
    ptr->next = queue->next;
    queue->next = ptr;
    pthread_mutex_unlock(&m_mut);
}
void HKLX::discover ()
Definition at line 535 of file HKLX.cpp.
References calculate_crc(), CMD_RAM_READ, hklx_packet_t::CRC, hklx_packet_t::data, test_struct::del, hklx_packet_allocate(), hklx_packet_t::id, test_struct::next, test_struct::packet, hklx_packet_t::packetsize, and test_struct::val.
                    {
    //update shoud be 54 then 12
    //hklx_packet_t *hklx_packet = hklx_packet_allocate(2, 0x00, CMD_RAM_READ);
    //hklx_packet->data[0] = 0;
    //hklx_packet->data[1] = 74;
    //hklx_packet_free(&hklx_packet);
    /*
    for (int i = 0; i < 254; i++) {
        hklx_packet->id = (uint8_t) (i);
        hklx_send(hklx_packet);
        //int rval = recive();
        id[i].connected=recive();
        if(id[i].connected){
            connected_id.push_back(i);
        }
        //printf("%i\n", rval);
        //usleep(10000);
    }*/
    //id[i].connected=recive();
    connected_id.push_back(0);
    connected_id.push_back(1);
    connected_id.push_back(2);
    connected_id.push_back(3);
    connected_id.push_back(8);
    connected_id.push_back(9);
    connected_id.push_back(10);
    connected_id.push_back(11);
    connected_id.push_back(16);
    connected_id.push_back(17);
    connected_id.push_back(18);
    connected_id.push_back(19);
    connected_id.push_back(20);
    connected_id.push_back(21);
    connected_id.push_back(22);
    connected_id.push_back(23);
    //connected_id.push_back(13);
    //connected_id.push_back(14);
    state_ready.push_back(0);
    state_ready.push_back(0);
    state_ready.push_back(0);
    state_ready.push_back(0);
    state_ready.push_back(0);
    state_ready.push_back(0);
    state_ready.push_back(0);
    state_ready.push_back(0);
    state_ready.push_back(0);
    state_ready.push_back(0);
    state_ready.push_back(0);
    state_ready.push_back(0);
    state_ready.push_back(0);
    state_ready.push_back(0);
    state_ready.push_back(0);
    state_ready.push_back(0);
    //state_ready.push_back(0);
    //state_ready.push_back(0);
    /*
    connected_id.push_back(2);
    connected_id.push_back(3);
    state_ready.push_back(0);
    state_ready.push_back(0);
     */
    //hklx_packet_t *hklx_packet = hklx_packet_allocate(2, 0x00, CMD_RAM_READ);
    //hklx_packet_t *hklx_packet = hklx_packet_allocate(2, BROADCAST_ID, CMD_RAM_READ);
    //hklx_packet->data[0] = 54;
    //hklx_packet->data[0] = 1;
    //hklx_packet->data[1] = 1;
    //hklx_send(hklx_packet);
    //int rval = recive();
    //queue = (struct test_struct*)malloc(sizeof(struct test_struct));
    //queue->next=queue;
    //hklx_packet = hklx_packet_allocate(2, 0x00, CMD_RAM_READ);
    //hklx_packet->data[0] = 0;
    //hklx_packet->data[1] = 74;
    //printf("%i\n",sizeof(test_struct));
    for (int i = 0; i < connected_id.size(); i++) {
        if (queue == NULL) {
            queue = (test_struct*) malloc(sizeof (test_struct));
            //hklx_packet->id=connected_id[i];
            queue->packet = hklx_packet_allocate(2, 0x00, CMD_RAM_READ);
            queue->packet->data[0] = 58;
            queue->packet->data[1] = 8;
            //queue->packet->data[0] = 54;
            //queue->packet->data[1] = 12;
            //queue->packet->data[0] = 45;
            //queue->packet->data[1] = 23;
            queue->packet->id = connected_id[i];
            queue->packet->CRC = calculate_crc(&queue->packet->packetsize);
            queue->val = i;
            queue->del = 0;
            prv = queue;
            queue->next = queue;
        } else {
            test_struct *ptr = (test_struct*) malloc(sizeof (test_struct));
            //hklx_packet->id=connected_id[i];
            ptr->packet = hklx_packet_allocate(2, 0x00, CMD_RAM_READ);
            ptr->packet->data[0] = 58;
            ptr->packet->data[1] = 8;
            //ptr->packet->data[0] = 54;
            //ptr->packet->data[1] = 12;
            //ptr->packet->data[0] = 45;
            //ptr->packet->data[1] = 23;
            ptr->packet->id = connected_id[i];
            ptr->packet->CRC = calculate_crc(&ptr->packet->packetsize);
            ptr->val = i;
            ptr->del = 0;
            ptr->next = queue->next;
            queue->next = ptr;
            prv = queue;
            queue = queue->next;
        }
    }
}
void HKLX::hklx_packet_parse (hklx_packet_t * hklx_packet)
Definition at line 248 of file HKLX.cpp.
References CALIBRATE_MASK, hklx_packet_t::cmd, CMD_RAM_READ_ACK, hklx_packet_t::data, and hklx_packet_t::id.
{
    switch (hklx_packet->cmd) {
        case CMD_RAM_READ_ACK:
            /*double exec_time = (double) getTickCount();
        usleep(1000000);
        //stag.hklx.update();
        exec_time = ((double) getTickCount() - exec_time) / getTickFrequency();*/
            memcpy(&id[hklx_packet->id].RAM.ID + (int) (hklx_packet->data[0]), &hklx_packet->data[2], hklx_packet->data[1]);
            double new_tc = (double) getTickCount();
            float new_w = ((float) id[hklx_packet->id].RAM.Differential_Position)*29.09f * M_PI / 180.0f;
            id[hklx_packet->id].RAM.Calibrated_Position = (id[hklx_packet->id].RAM.Calibrated_Position & CALIBRATE_MASK);
            id[hklx_packet->id].abs_phi = ((float) id[hklx_packet->id].RAM.Absolute_Position)*0.3258064516f - 166.650f;
            //id[hklx_packet->id].phi = ((float) id[hklx_packet->id].RAM.Calibrated_Position)*0.3258064516f - 166.650f;
            float newphi = ((float) id[hklx_packet->id].RAM.Calibrated_Position)*0.3258064516f - 166.650f;
            //id[hklx_packet->id].W = ((newphi-id[hklx_packet->id].phi)/((new_tc-id[hklx_packet->id].tc)/ getTickFrequency()))*M_PI/180.0f;
            float newW = ((newphi - id[hklx_packet->id].phi) / ((new_tc - id[hklx_packet->id].tc) / getTickFrequency())) * M_PI / 180.0f;
            id[hklx_packet->id].A = (newW - id[hklx_packet->id].W) / ((new_tc - id[hklx_packet->id].tc) / getTickFrequency());
            id[hklx_packet->id].a = (new_w - id[hklx_packet->id].w) / ((new_tc - id[hklx_packet->id].tc) / getTickFrequency());
            id[hklx_packet->id].W = newW;
            id[hklx_packet->id].phi = newphi;
            id[hklx_packet->id].w = new_w;
            id[hklx_packet->id].tc = new_tc;
            id[hklx_packet->id].vin = ((float) id[hklx_packet->id].RAM.Voltage)*0.0740745098f;
            id[hklx_packet->id].temp = ((float) id[hklx_packet->id].RAM.Temperature)*1.497559055f - 79.47f;
            //id[hklx_packet->id].RAM.PWM = (id[hklx_packet->id].RAM.PWM & T_MASK);
            id[hklx_packet->id].pwm = ((float) id[hklx_packet->id].RAM.PWM) / 1023.0;
            //id[hklx_packet->id].w = ((float)id[hklx_packet->id].RAM.Differential_Position)*29.09f*M_PI/180.0f;
            //if(hklx_packet->id==2){
            //if(fabs(id[hklx_packet->id].pwm)>0.3){
            //printf("%i\n",hklx_packet->data[1]);
            //printf("%i\n",id[hklx_packet->id].RAM.PWM);
            //for(int i=0;i<hklx_packet->data[1];i++){
            //    printf("%02x",hklx_packet->data[2+i]);
            //for(int i=0;i<hklx_packet->packetsize-7;i++){
            //    printf("%02x",hklx_packet->data[i]);
            //}
            //printf("\n");
            // }
            //}
            /*
            if(hklx_packet->id==3){
                //printf("%i\n",hklx_packet->data[1]);
                for(int i=0;i<hklx_packet->data[1];i++){
                    printf("%02x",hklx_packet->data[2+i]);
                }
                printf("\n");
            }*/
            /*
            if(hklx_packet->id==2){
                printf("%i\n",hklx_packet->data[1]);
                for(int i=0;i<hklx_packet->data[1];i++){
                    printf("%x",hklx_packet->data[2+i]);
                }
                printf("\n");
            }*/
            //printf("%i\n",hklx_packet->packetsize);
            //printf("%f\n",id[hklx_packet->id].phi);
            break;
            /*
            case 1:
                break;
            case 2:
                break;
            case 3:
                break;
             */
    }
}
void * HKLX::loop (void * obj) [static]
Definition at line 743 of file HKLX.cpp.
{
    while (reinterpret_cast<HKLX *> (obj)->active) reinterpret_cast<HKLX *> (obj)-> poll();
}
void HKLX::poll ()
Definition at line 764 of file HKLX.cpp.
References hklx_packet_free(), test_struct::next, and test_struct::packet.
                {
    pthread_mutex_lock(&m_mut);
    //double exec_time = (double) getTickCount();
    //query(queue->packet);
    //exec_time = ((double) getTickCount() - exec_time) / getTickFrequency();
    //printf("%f\n", exec_time);
    //state_ready[queue->val]=1;
    if (query(queue->packet)) {
        state_ready[queue->val] = 1;
    }
    //usleep(1000);
    pthread_mutex_unlock(&m_mut);
    //if(queue->val==0){
    //fr++;
    //printf("%f\n", fr / (((double) getTickCount() - start) / getTickFrequency()));
    //}
    switch (queue->del) {
        case 0:
            prv = queue;
            queue = queue->next;
            break;
        case 1:
            test_struct *del = queue;
            prv->next = del->next;
            queue = queue->next;
            hklx_packet_free(&del->packet);
            free(del);
            break;
    }
    //usleep(2200);
    usleep(20);
    //usleep(2000);
    //usleep(1);
    //add2queue();
    //usleep(500000);
}
int HKLX::query (hklx_packet_t * query_packet) [private]
Definition at line 430 of file HKLX.cpp.
References hklx_packet_t::header, HKLX_COM, hklx_decoder_increment, hklx_decoder_pointer, hklx_decoder_size, hklx_packet_decode_new(), hklx_packet_free(), hklx_packet_t::packetsize, PollComport(), return_length(), and SendBuf().
{
    //query_packet->CRC = calculate_crc(&query_packet->packetsize);
    SendBuf(HKLX_COM, &query_packet->header[0], query_packet->packetsize);
    int length = return_length(query_packet);
    hklx_packet_t *hklx_packet;
    int bytes_received = 0;
    fd_set fds;
    FD_ZERO(&fds);
    FD_SET(hklx_fd, &fds);
    struct timeval timeout = {0, 3000};
    int ret = select(hklx_fd + 1, &fds, NULL, NULL, &timeout); //CHANGE TO PSELECT
    //printf("%i\n",length);
    while (hklx_decoder.buffer_length < length) {//here in lies the rub
        if ((bytes_received = PollComport(HKLX_COM, hklx_decoder_pointer(&hklx_decoder), hklx_decoder_size(&hklx_decoder))) > 0) {
            hklx_decoder_increment(&hklx_decoder, bytes_received);
        }
    }
    if ((hklx_packet = hklx_packet_decode_new(&hklx_decoder)) != NULL) {
        hklx_packet_parse(hklx_packet);
        hklx_packet_free(&hklx_packet);
        return 1;
    }
    /*
    while (1) {
        if ((bytes_received = PollComport(HKLX_COM, hklx_decoder_pointer(&hklx_decoder), hklx_decoder_size(&hklx_decoder))) > 0) {
        //if ((bytes_received = PollComport(HKLX_COM, hklx_decoder_pointer(&hklx_decoder), 1)) > 0) {
            //printf("%i\n",bytes_received);
            hklx_decoder_increment(&hklx_decoder, bytes_received);
            while ((hklx_packet = hklx_packet_decode(&hklx_decoder)) != NULL) {
                //hklx_packet_parse(hklx_packet);
                hklx_packet_free(&hklx_packet);
                return 1;
            }
        }
    }*/
    return 0; //lolz
}
int HKLX::recive ()
Definition at line 390 of file HKLX.cpp.
References HKLX_COM, hklx_decoder_increment, hklx_decoder_pointer, hklx_decoder_size, hklx_packet_decode(), hklx_packet_free(), and PollComport().
                 {
    hklx_packet_t *hklx_packet;
    int bytes_received = 0;
    fd_set fds;
    FD_ZERO(&fds);
    FD_SET(hklx_fd, &fds);
    struct timeval timeout = {1, 0};
    int ret = select(hklx_fd + 1, &fds, NULL, NULL, &timeout);
    if (ret > 0)
        while (1) {
            if ((bytes_received = PollComport(HKLX_COM, hklx_decoder_pointer(&hklx_decoder), hklx_decoder_size(&hklx_decoder))) > 0) {
                //printf("%i\n",bytes_received);
                hklx_decoder_increment(&hklx_decoder, bytes_received);
                while ((hklx_packet = hklx_packet_decode(&hklx_decoder)) != NULL) {
                    hklx_packet_parse(hklx_packet);
                    hklx_packet_free(&hklx_packet);
                    return 1;
                }
            }
        }
    return 0;
}
void HKLX::send (hklx_packet_t * hklx_packet)
Definition at line 94 of file HKLX.cpp.
References calculate_crc(), hklx_packet_t::CRC, hklx_packet_t::header, HKLX_COM, hklx_packet_t::packetsize, and SendBuf().
Referenced by main(), and Stag::sjb().
{
    pthread_mutex_lock(&m_mut);
    hklx_packet->CRC = calculate_crc(&hklx_packet->packetsize);
    SendBuf(HKLX_COM, &hklx_packet->header[0], hklx_packet->packetsize);
    pthread_mutex_unlock(&m_mut);
}
void HKLX::state (_hklx out[])
Definition at line 821 of file HKLX.cpp.
References _RAM::ID, and _hklx::RAM.
{
    pthread_mutex_lock(&m_mut);
    for (int i = 0; i < connected_id.size(); i++) {
        if (state_ready[i]) {
            memcpy(&out[connected_id[i]].RAM.ID, &id[connected_id[i]].RAM.ID, sizeof (_hklx));
            state_ready[i] = 0;
        }
    }
    pthread_mutex_unlock(&m_mut);
    //_hklx id[254];
    //if(connected)
    //return id;
    //return NULL;
}
Field Documentation
bool HKLX::active [private]
Definition at line 339 of file HKLX.h.
std::vector<int> HKLX::connected_id [private]
Definition at line 343 of file HKLX.h.
double HKLX::fr
Definition at line 332 of file HKLX.h.
hklx_decoder_t HKLX::hklx_decoder [private]
Definition at line 348 of file HKLX.h.
int HKLX::hklx_fd [private]
Definition at line 349 of file HKLX.h.
_hklx HKLX::id[254] [private]
Definition at line 347 of file HKLX.h.
pthread_mutex_t HKLX::m_mut [private]
Definition at line 346 of file HKLX.h.
test_struct* HKLX::prv [private]
Definition at line 342 of file HKLX.h.
test_struct* HKLX::queue [private]
Definition at line 341 of file HKLX.h.
double HKLX::start
Definition at line 333 of file HKLX.h.
std::vector<int> HKLX::state_ready [private]
Definition at line 344 of file HKLX.h.
pthread_t HKLX::thread [private]
Definition at line 340 of file HKLX.h.
The documentation for this class was generated from the following files:
HKLX.h
HKLX.cpp