stag_doc: sixmotion Class Reference
sixmotion Class Reference
#include <stagsrc/src/sixmotion.h>
Public Member Functions
sixmotion ()
sixmotion (const sixmotion &orig)
virtual ~sixmotion ()
void readEv ()
_sixmotion state ()
Static Public Member Functions
static void * loop (void *obj)
Private Attributes
_sixmotion_hidraw raw_sixm
_sixmotion sixm
struct motion_dev * devs
int next_devindex
bool active
bool connected
int csk
int isk
pthread_t thread
Detailed Description
Definition at line 146 of file sixmotion.h.
Constructor & Destructor Documentation
sixmotion::sixmotion ()
Definition at line 199 of file sixmotion.cpp.
References active, connected, csk, devs, isk, l2cap_listen(), L2CAP_PSM_HIDP_CTRL, L2CAP_PSM_HIDP_INTR, loop(), next_devindex, and thread.
                     {
    devs = NULL;
    next_devindex = 0;
    csk = l2cap_listen(L2CAP_PSM_HIDP_CTRL);
    isk = l2cap_listen(L2CAP_PSM_HIDP_INTR);
    active = false;
    connected = false;
    if (csk >= 0 && isk >= 0) {
        fprintf(stderr, "Waiting for Bluetooth connection.\n");
        active = true;
        pthread_create(&thread, 0, &sixmotion::loop, this);
    } else {
        fprintf(stderr, "Unable to listen on HID PSMs."
                " Are you root bro?\n");
        active = false;
    }
}
sixmotion::sixmotion (const sixmotion & orig)
Definition at line 221 of file sixmotion.cpp.
{
}
sixmotion::~sixmotion () [virtual]
Definition at line 224 of file sixmotion.cpp.
References active, and thread.
                      {
    active = false;
    pthread_join(thread, 0);
}
Member Function Documentation
void * sixmotion::loop (void * obj) [static]
Definition at line 230 of file sixmotion.cpp.
References active, and readEv().
Referenced by sixmotion().
{
    while (reinterpret_cast<sixmotion *> (obj)->active) reinterpret_cast<sixmotion *> (obj)->readEv();
}
void sixmotion::readEv ()
Definition at line 235 of file sixmotion.cpp.
References accept_device(), connected, csk, devs, fatal(), motion_dev::index, isk, motion_dev::next, next_devindex, parse_raw(), raw_sixm, setup_device(), and sixm.
Referenced by loop().
                       {
    fd_set fds;
    FD_ZERO(&fds);
    FD_SET(0, &fds);
    int fdmax = 0;
    if (csk >= 0) FD_SET(csk, &fds);
    if (isk >= 0) FD_SET(isk, &fds);
    if (csk > fdmax) fdmax = csk;
    if (isk > fdmax) fdmax = isk;
    for (struct motion_dev *dev = devs; dev; dev = dev->next) {
        FD_SET(dev->csk, &fds);
        if (dev->csk > fdmax) fdmax = dev->csk;
        FD_SET(dev->isk, &fds);
        if (dev->isk > fdmax) fdmax = dev->isk;
    }
    //waiting for a controler
    if (select(fdmax + 1, &fds, NULL, NULL, NULL) < 0) fatal("select");
    //struct timeval tv;
    //gettimeofday(&tv, NULL);
    //time_t now = tv.tv_sec;
    // Incoming connection ?
    if (csk >= 0 && FD_ISSET(csk, &fds)) {//CONNECTS DEVICE
        struct motion_dev *dev = accept_device(csk, isk);
        dev->index = next_devindex++;
        dev->next = devs;
        devs = dev;
        setup_device(dev);
        connected = true;
    }
    for (struct motion_dev *dev = devs; dev; dev = dev->next)
        if (FD_ISSET(dev->isk, &fds)) {
            unsigned char report[256];
            //select (int __nfds, fd_set *__restrict __readfds, fd_set *__restrict __writefds, fd_set *__restrict __exceptfds, struct timeval *__restrict __timeout);
            struct timeval tv;
            tv.tv_sec = 1;
            tv.tv_usec = 0;
            //select(fdmax + 1, &fds, NULL, NULL, &tv);
            //int nr = recv(dev->isk, report, sizeof (report), 0);
            int nr = recv(dev->isk, report, sizeof (report), MSG_DONTWAIT);
            if (nr == 50) {
                if (report[0] == 0xa1) {
                    memcpy(&raw_sixm, report, nr);
                    //dump("RECV", report, nr);
                    parse_raw(raw_sixm, sixm);
                }
            }
            /*
            if (nr <= 0) {
                //fprintf(stderr, "%d disconnected\n", dev->index);
                printf("DISCONNECTED\n");
                close(dev->csk);
                close(dev->isk);
                struct motion_dev **pdev;
                for (pdev = &devs; *pdev != dev; pdev = &(*pdev)->next);
             *pdev = dev->next;
                free(dev);
            } else {
                if (report[0] == 0xa1) {
                }
            }*/
        }
    /*
    for (struct motion_dev *dev = devs; dev; dev = dev->next)
        if (FD_ISSET(dev->isk, &fds)) {
            int nr = 1;
            while (nr > 0) {
                unsigned char report[256];
                //nr = recv(dev->isk, report, sizeof (report), MSG_DONTWAIT);
                printf("RCV\n");
                nr = recv(dev->isk, report, sizeof (report), 0);
                //THIS IS THE REPORT
                if (report[0] == 0xa1) {
                    if (nr == 50) {
                        //memcpy(&raw_sixm, report, nr);
                        //dump("RECV", report, nr);
                        //parse_raw(raw_sixm, sixm);
                        printf("REPORT\n");
                    }
                } else {
                    printf("REPORT\n");
                }
            }
        }*/
}
_sixmotion sixmotion::state ()
Definition at line 344 of file sixmotion.cpp.
References sixm.
Referenced by main().
{
    return sixm;
}
Field Documentation
bool sixmotion::active [private]
Definition at line 161 of file sixmotion.h.
Referenced by loop(), sixmotion(), and ~sixmotion().
bool sixmotion::connected [private]
Definition at line 162 of file sixmotion.h.
Referenced by readEv(), and sixmotion().
int sixmotion::csk [private]
Definition at line 163 of file sixmotion.h.
Referenced by readEv(), and sixmotion().
struct motion_dev* sixmotion::devs [private]
Definition at line 159 of file sixmotion.h.
Referenced by readEv(), and sixmotion().
int sixmotion::isk [private]
Definition at line 164 of file sixmotion.h.
Referenced by readEv(), and sixmotion().
int sixmotion::next_devindex [private]
Definition at line 160 of file sixmotion.h.
Referenced by readEv(), and sixmotion().
_sixmotion_hidraw sixmotion::raw_sixm [private]
Definition at line 157 of file sixmotion.h.
Referenced by readEv().
_sixmotion sixmotion::sixm [private]
Definition at line 158 of file sixmotion.h.
Referenced by readEv(), and state().
pthread_t sixmotion::thread [private]
Definition at line 165 of file sixmotion.h.
Referenced by sixmotion(), and ~sixmotion().
The documentation for this class was generated from the following files:
sixmotion.h
sixmotion.cpp