stag_doc: rs232.h File Reference
rs232.h File Reference
#include <stdio.h>
#include <string.h>
#include <windows.h>
Functions
int OpenComport (int, int, float)
int PollComport (int, unsigned char *, int)
int SendByte (int, unsigned char)
int SendBuf (int, unsigned char *, int)
void CloseComport (int)
void cprintf (int, const char *)
int IsCTSEnabled (int)
Function Documentation
void CloseComport (int)
Definition at line 445 of file rs232.c.
{
  CloseHandle(Cport[comport_number]);
}
void cprintf (int , const char *)
Definition at line 465 of file rs232.c.
References SendByte().
{
  while(*text != 0)   SendByte(comport_number, *(text++));
}
int IsCTSEnabled (int)
Definition at line 451 of file rs232.c.
{
  int status;
  GetCommModemStatus(Cport[comport_number], (LPDWORD)((void *)&status));
  if(status&MS_CTS_ON) return(1);
  else return(0);
}
int OpenComport (int , int , float)
int PollComport (int , unsigned char * , int)
Definition at line 405 of file rs232.c.
Referenced by HKLX::query(), and HKLX::recive().
{
  int n;
  if(size>4096)  size = 4096;
/* added the void pointer cast, otherwise gcc will complain about */
/* "warning: dereferencing type-punned pointer will break strict aliasing rules" */
  ReadFile(Cport[comport_number], buf, size, (LPDWORD)((void *)&n), NULL);
  return(n);
}
int SendBuf (int , unsigned char * , int)
Definition at line 432 of file rs232.c.
Referenced by HKLX::query(), and HKLX::send().
{
  int n;
  if(WriteFile(Cport[comport_number], buf, size, (LPDWORD)((void *)&n), NULL))
  {
    return(n);
  }
  return(-1);
}
int SendByte (int , unsigned char)
Definition at line 420 of file rs232.c.
Referenced by cprintf().
{
  int n;
  WriteFile(Cport[comport_number], &byte, 1, (LPDWORD)((void *)&n), NULL);
  if(n<0)  return(1);
  return(0);
}