stag_doc: rs232.c File Reference
rs232.c File Reference
#include "rs232.h"
Functions
int OpenComport (int comport_number, int baudrate)
int PollComport (int comport_number, unsigned char *buf, int size)
int SendByte (int comport_number, unsigned char byte)
int SendBuf (int comport_number, unsigned char *buf, int size)
void CloseComport (int comport_number)
int IsCTSEnabled (int comport_number)
void cprintf (int comport_number, const char *text)
Variables
HANDLE Cport [16]
char comports [16][10]
char baudr [64]
Function Documentation
void CloseComport (int comport_number)
Definition at line 445 of file rs232.c.
{
  CloseHandle(Cport[comport_number]);
}
void cprintf (int comport_number, const char * text)
Definition at line 465 of file rs232.c.
References SendByte().
{
  while(*text != 0)   SendByte(comport_number, *(text++));
}
int IsCTSEnabled (int comport_number)
Definition at line 451 of file rs232.c.
{
  int status;
  GetCommModemStatus(Cport[comport_number], (LPDWORD)((void *)&status));
  if(status&MS_CTS_ON) return(1);
  else return(0);
}
int OpenComport (int comport_number, int baudrate)
Definition at line 312 of file rs232.c.
Referenced by HKLX::HKLX().
{
  DCB port_settings;
  COMMTIMEOUTS Cptimeouts;
  if((comport_number>15)||(comport_number<0))
  {
    printf("illegal comport number\n");
    return(1);
  }
  switch(baudrate)
  {
    case     110 : strcpy(baudr, "baud=110 data=8 parity=N stop=1");
                   break;
    case     300 : strcpy(baudr, "baud=300 data=8 parity=N stop=1");
                   break;
    case     600 : strcpy(baudr, "baud=600 data=8 parity=N stop=1");
                   break;
    case    1200 : strcpy(baudr, "baud=1200 data=8 parity=N stop=1");
                   break;
    case    2400 : strcpy(baudr, "baud=2400 data=8 parity=N stop=1");
                   break;
    case    4800 : strcpy(baudr, "baud=4800 data=8 parity=N stop=1");
                   break;
    case    9600 : strcpy(baudr, "baud=9600 data=8 parity=N stop=1");
                   break;
    case   19200 : strcpy(baudr, "baud=19200 data=8 parity=N stop=1");
                   break;
    case   38400 : strcpy(baudr, "baud=38400 data=8 parity=N stop=1");
                   break;
    case   57600 : strcpy(baudr, "baud=57600 data=8 parity=N stop=1");
                   break;
    case  115200 : strcpy(baudr, "baud=115200 data=8 parity=N stop=1");
                   break;
    case  128000 : strcpy(baudr, "baud=128000 data=8 parity=N stop=1");
                   break;
    case  256000 : strcpy(baudr, "baud=256000 data=8 parity=N stop=1");
                   break;
    default      : printf("invalid baudrate\n");
                   return(1);
                   break;
  }
  Cport[comport_number] = CreateFileA(comports[comport_number],
                      GENERIC_READ|GENERIC_WRITE,
                      0,                          /* no share  */
                      NULL,                       /* no security */
                      OPEN_EXISTING,
                      0,                          /* no threads */
                      NULL);                      /* no templates */
  if(Cport[comport_number]==INVALID_HANDLE_VALUE)
  {
    printf("unable to open comport\n");
    return(1);
  }
  memset(&port_settings, 0, sizeof(port_settings));  /* clear the new struct  */
  port_settings.DCBlength = sizeof(port_settings);
  if(!BuildCommDCBA(baudr, &port_settings))
  {
    printf("unable to set comport dcb settings\n");
    CloseHandle(Cport[comport_number]);
    return(1);
  }
  if(!SetCommState(Cport[comport_number], &port_settings))
  {
    printf("unable to set comport cfg settings\n");
    CloseHandle(Cport[comport_number]);
    return(1);
  }
  Cptimeouts.ReadIntervalTimeout         = MAXDWORD;
  Cptimeouts.ReadTotalTimeoutMultiplier  = 0;
  Cptimeouts.ReadTotalTimeoutConstant    = 0;
  Cptimeouts.WriteTotalTimeoutMultiplier = 0;
  Cptimeouts.WriteTotalTimeoutConstant   = 0;
  if(!SetCommTimeouts(Cport[comport_number], &Cptimeouts))
  {
    printf("unable to set comport time-out settings\n");
    CloseHandle(Cport[comport_number]);
    return(1);
  }
  return(0);
}
int PollComport (int comport_number, unsigned char * buf, int size)
Definition at line 405 of file rs232.c.
Referenced by HKLX::query(), and HKLX::recive().
{
  int n;
  if(size>4096)  size = 4096;
/* added the void pointer cast, otherwise gcc will complain about */
/* "warning: dereferencing type-punned pointer will break strict aliasing rules" */
  ReadFile(Cport[comport_number], buf, size, (LPDWORD)((void *)&n), NULL);
  return(n);
}
int SendBuf (int comport_number, unsigned char * buf, int size)
Definition at line 432 of file rs232.c.
Referenced by HKLX::query(), and HKLX::send().
{
  int n;
  if(WriteFile(Cport[comport_number], buf, size, (LPDWORD)((void *)&n), NULL))
  {
    return(n);
  }
  return(-1);
}
int SendByte (int comport_number, unsigned char byte)
Definition at line 420 of file rs232.c.
Referenced by cprintf().
{
  int n;
  WriteFile(Cport[comport_number], &byte, 1, (LPDWORD)((void *)&n), NULL);
  if(n<0)  return(1);
  return(0);
}
Variable Documentation
char baudr[64]
Definition at line 309 of file rs232.c.
char comports[16][10]
Initial value:
{"\\\\.\\COM1",  "\\\\.\\COM2",  "\\\\.\\COM3",  "\\\\.\\COM4",
                       "\\\\.\\COM5",  "\\\\.\\COM6",  "\\\\.\\COM7",  "\\\\.\\COM8",
                       "\\\\.\\COM9",  "\\\\.\\COM10", "\\\\.\\COM11", "\\\\.\\COM12",
                       "\\\\.\\COM13", "\\\\.\\COM14", "\\\\.\\COM15", "\\\\.\\COM16"}
Definition at line 304 of file rs232.c.
HANDLE Cport[16]
Definition at line 301 of file rs232.c.