stag_doc: sixmotion.cpp File Reference
sixmotion.cpp File Reference
#include "sixmotion.h"
#include <math.h>
Defines
#define LED_PERMANENT 0xff, 0x27, 0x10, 0x00, 0x32
Functions
void be_memcpy (const void *destination, const void *source, uint8_t size)
void fatal (char *msg)
int l2cap_listen (unsigned short psm)
struct motion_dev * accept_device (int csk, int isk)
void hidp_trans (int csk, int isk, const char *buf, int len)
void setup_device (struct motion_dev *dev)
void parse_raw (_sixmotion_hidraw &raw, _sixmotion &sixm)
Variables
int force_sixaxis = 1
int force_ds3 = 0
int timestamp = 0
int nostdin = 0
Define Documentation
#define LED_PERMANENT 0xff, 0x27, 0x10, 0x00, 0x32
Referenced by setup_device().
Function Documentation
struct motion_dev* accept_device (int csk, int isk) [read]
Definition at line 47 of file sixmotion.cpp.
References motion_dev::addr, motion_dev::csk, DS3, fatal(), force_ds3, force_sixaxis, HIDP_DATA_RTYPE_FEATURE, HIDP_TRANS_GET_REPORT, motion_dev::isk, PSMOVE, SIXAXIS, and motion_dev::type.
Referenced by sixmotion::readEv().
{
    fprintf(stderr, "Incoming connection...\n");
    struct motion_dev *dev = (motion_dev*) malloc(sizeof (struct motion_dev));
    if (!dev) fatal("malloc");
    dev->csk = accept(csk, NULL, NULL);
    if (dev->csk < 0) fatal("accept(CTRL)");
    dev->isk = accept(isk, NULL, NULL);
    if (dev->isk < 0) fatal("accept(INTR)");
    struct sockaddr_l2 addr;
    socklen_t addrlen = sizeof (addr);
    if (getpeername(dev->isk, (struct sockaddr *) &addr, &addrlen) < 0)
        fatal("getpeername");
    dev->addr = addr.l2_bdaddr;
    {
        // Distinguish SIXAXIS / DS3 / PSMOVE.
        unsigned char resp[64];
        char get03f2[] = {HIDP_TRANS_GET_REPORT | HIDP_DATA_RTYPE_FEATURE | 8,
            0xf2, sizeof (resp), sizeof (resp) >> 8};
        send(dev->csk, get03f2, sizeof (get03f2), 0); // 0301 is interesting too.
        int nr = recv(dev->csk, resp, sizeof (resp), 0);
        if (nr < 19) dev->type = PSMOVE;
        else if (force_sixaxis) dev->type = SIXAXIS;
        else if (force_ds3) dev->type = DS3;
        else dev->type = (resp[13] == 0x40) ? SIXAXIS : DS3; // My guess.
    }
    return dev;
}
void be_memcpy (const void * destination, const void * source, uint8_t size)
Definition at line 15 of file sixmotion.cpp.
Referenced by parse_raw().
{
    uint8_t copy_count = 0;
    while (size) ((uint8_t *) destination)[copy_count++] = ((uint8_t *) source)[--size];
}
void fatal (char * msg)
Definition at line 20 of file sixmotion.cpp.
Referenced by accept_device(), hidp_trans(), l2cap_listen(), and sixmotion::readEv().
                      {
    if (errno) perror(msg);
    else fprintf(stderr, "%s\n", msg);
    exit(1);
}
void hidp_trans (int csk, int isk, const char * buf, int len)
Definition at line 79 of file sixmotion.cpp.
References fatal().
Referenced by setup_device().
{
    if (send(csk, buf, len, 0) != len) fatal("send(CTRL)");
    unsigned char ack;
    int nr = recv(csk, &ack, sizeof (ack), 0);
    //int nr = recv(csk, &ack, sizeof (ack), MSG_DONTWAIT);//THIS no longer in same thread needs to be looked at
    //if (nr != 1 || ack != 0) fatal("ack");
}
int l2cap_listen (unsigned short psm)
Definition at line 26 of file sixmotion.cpp.
References fatal().
Referenced by sixmotion::sixmotion().
{
    int sk = socket(PF_BLUETOOTH, SOCK_SEQPACKET, BTPROTO_L2CAP);
    if (sk < 0) fatal("socket");
    struct sockaddr_l2 addr;
    memset(&addr, 0, sizeof (addr));
    addr.l2_family = AF_BLUETOOTH;
    addr.l2_bdaddr = {
        {0, 0, 0, 0, 0, 0}
    };
    addr.l2_psm = htobs(psm);
    if (bind(sk, (struct sockaddr *) &addr, sizeof (addr)) < 0) {
        perror("bind");
        close(sk);
        return -1;
    }
    if (listen(sk, 5) < 0) fatal("listen");
    return sk;
}
void parse_raw (_sixmotion_hidraw & raw, _sixmotion & sixm)
Definition at line 142 of file sixmotion.cpp.
References _sixmotion_hidraw::ax, _sixmotion::aX, _sixmotion_hidraw::ay, _sixmotion::aY, _sixmotion_hidraw::az, _sixmotion::aZ, be_memcpy(), _sixmotion_hidraw::gz, _sixmotion::gZ, _sixmotion::L3_mag, _sixmotion_hidraw::L3_x, _sixmotion::L3_x, _sixmotion_hidraw::L3_y, _sixmotion::L3_y, _sixmotion::R3_mag, _sixmotion_hidraw::R3_x, _sixmotion::R3_x, _sixmotion_hidraw::R3_y, and _sixmotion::R3_y.
Referenced by sixmotion::readEv().
{
    sixm.L3_x = -128.0f + (float) raw.L3_x;
    sixm.L3_y = 128.0f - (float) raw.L3_y;
    sixm.L3_mag = sqrt(sixm.L3_x * sixm.L3_x + sixm.L3_y * sixm.L3_y);
    if (sixm.L3_mag > 128.0f)
        sixm.L3_mag = 128.0f;
    //printf("%i\n",raw.BTN_L1_VALUE);
    sixm.R3_x = -128.0f + (float) raw.R3_x;
    sixm.R3_y = 128.0f - (float) raw.R3_y;
    sixm.R3_mag = sqrt(sixm.R3_x * sixm.R3_x + sixm.R3_y * sixm.R3_y);
    if (sixm.R3_mag > 128.0f)
        sixm.R3_mag = 128.0f;
    uint16_t ax, ay, az, gz;
    be_memcpy(&ax, raw.ax, 2);
    be_memcpy(&ay, raw.ay, 2);
    be_memcpy(&az, raw.az, 2);
    be_memcpy(&gz, raw.gz, 2);
    sixm.aX = ax - 512;
    sixm.aY = ay - 512;
    sixm.aZ = az - 512 - 100;
    sixm.gZ = gz - 512;
    //printf("%f %f\n",sixm.R3_x,sixm.R3_y);
    //printf("%i \n",ax);
    //sixm.aX = raw.ax1*256 + raw.ax2 - 512;
    //sixm.aY = raw.ay1*256 + raw.ay2 - 512;
    //sixm.aZ = raw.az1*256 + raw.az2 - 512;
    //sixm.gZ = raw.gz1*256 + raw.gz2 - 512;
    //printf("%f %f %f %f\n",sixm.aX,sixm.aY,sixm.aZ,sixm.gZ);
    //sqrt(sixm.aX*sixm.aX+sixm.aY*sixm.aY+sixm.aZ+sixm.aZ);
    //printf("%f %f %f %f\n",sixm.aX,sixm.aY,sixm.aZ);
    //printf("%f\n",sqrt(sixm.aX*sixm.aX+sixm.aY*sixm.aY+sixm.aZ*sixm.aZ));
    //printf("%i %i\n",raw.gz1,raw.gz2);
    //printf("%i %i %i %i\n",raw.aX,raw.aY,raw.aZ,raw.gZ);
}
void setup_device (struct motion_dev * dev)
Definition at line 88 of file sixmotion.cpp.
References motion_dev::csk, DS3, HIDP_DATA_RTYPE_FEATURE, HIDP_DATA_RTYPE_OUTPUT, hidp_trans(), HIDP_TRANS_SET_REPORT, motion_dev::index, motion_dev::isk, LED_PERMANENT, SIXAXIS, and motion_dev::type.
Referenced by sixmotion::readEv().
{
    switch (dev->type) {
        case SIXAXIS:
        case DS3:
        {
            char set03f4[] = {HIDP_TRANS_SET_REPORT | HIDP_DATA_RTYPE_FEATURE, 0xf4,
                0x42, 0x03, 0x00, 0x00};
            hidp_trans(dev->csk, dev->isk, set03f4, sizeof (set03f4));
            static const char ledmask[10] = {1, 2, 4, 8, 6, 7, 11, 13, 14, 15};
#define LED_PERMANENT 0xff, 0x27, 0x10, 0x00, 0x32
            char set0201[] = {
                HIDP_TRANS_SET_REPORT | HIDP_DATA_RTYPE_OUTPUT, 0x01,
                0x00, 0x00, 0x00, 0, 0, 0x00, 0x00, 0x00,
                0x00, ledmask[dev->index % 10] << 1,
                LED_PERMANENT,
                LED_PERMANENT,
                LED_PERMANENT,
                LED_PERMANENT,
                0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
            };
            char output_report[] = {
                0x52, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00,
                0x00, 0x70, 0x00, 0x00, 0x00,
                0xff, 0x27, 0x10, 0x00, 0x32,
                0xff, 0x27, 0x10, 0x00, 0x32,
                0xff, 0x27, 0x10, 0x00, 0x32,
                0xff, 0x27, 0x10, 0x00, 0x32,
                0x00, 0x00, 0x00, 0x00, 0x00,
                0x00, 0x00, 0x00, 0x00, 0x00,
                0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
            };
            if (dev->type == SIXAXIS) {
                printf("six\n");
            } else {
                printf("ds3\n");
            }
            printf("start trans\n");
            printf("finish setup\n");
            break;
        }
    }
}
Variable Documentation
int force_ds3 = 0
Definition at line 11 of file sixmotion.cpp.
Referenced by accept_device().
int force_sixaxis = 1
Definition at line 10 of file sixmotion.cpp.
Referenced by accept_device().
int nostdin = 0
Definition at line 13 of file sixmotion.cpp.
int timestamp = 0
Definition at line 12 of file sixmotion.cpp.