env = Environment(CC = 'g++',
                      CCFLAGS = '-O2')
env.ParseConfig('pkg-config --cflags --libs opencv')
mysources = [Glob('src/*.c'), Glob('src/*.cpp')]

env.Program( target = 'bin/stag_bin', source = mysources )
